version: 2
jobs:
  deploy-job:
    docker:
      - image: wilson208/circleci-awscli
    working_directory: /tmp/whatever
    steps:
      - checkout
      - run:
          name: Deploy to S3
          command: ./deploy.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: master
